### ISSUE TITLE
PCAP Encryption & Compression

### ISSUE THREAD

**Issue by awick** [aol/moloch#484]
Add the ability to Moloch to have pcap files that are encrypted.  Would be nice if they are each an option.

**Comment by awick** [comment]
0.17 supports encryption now (but not compression)

**Comment by lhmerino** [comment]
Hello,

Is there a way currently to compress pcaps on the fly with moloch even if it cannot be read into the viewer?

Thank you in advance,
Louis-Henri

**Comment by awick** [comment]
No.  pcaps don't compress very well, especially if there is a lot of TLS.  The best way to save space for pcaps is to drop TLS traffic after the first few packets.

This can be done in 0.19 with the following rules file

```
---
version: 1
rules:
- name: "Drop tls"
  when: "fieldSet"
  fields:
    protocols:
    - tls
  ops:
    _maxPacketsToSave: 10
```
